// SPDX-FileCopyrightText: 2026 Habenula, Inc.
// SPDX-License-Identifier: AGPL-3.0-only

/**
 * Pure emit layer for the schema codegen: introspected column metadata in,
 * Zod schema source text out. No SQL, no filesystem, no `node:sqlite` — so it
 * runs anywhere (including the Workers test pool) and is unit-tested directly
 * against hand-written literal expectations in `test/codegen/generate.test.ts`.
 */

export type SqlType = "TEXT" | "INTEGER" | "REAL";

export interface ColumnMeta {
  /** Column name, verbatim. */
  name: string;
  /** Declared SQLite storage type. */
  sqlType: SqlType;
  /** True when the column admits NULL (pragma notnull === 0 and not a PK). */
  nullable: boolean;
  /** Present when a `CHECK(col IN (...))` constrains the column to a value set. */
  enumValues?: string[];
}

// Acronyms that must keep their canonical casing in generated identifiers,
// matching the hand-written house style elsewhere (e.g. OAuthStateData).
const ACRONYMS: Record<string, string> = { oauth: "OAuth" };

function pascalSegment(segment: string): string {
  return (
    ACRONYMS[segment] ?? segment.charAt(0).toUpperCase() + segment.slice(1)
  );
}

/** `audit_log` → `AuditLog`, `oauth_state` → `OAuthState`. */
export function pascalCase(snake: string): string {
  return snake.split("_").map(pascalSegment).join("");
}

/** Row-schema / row-type export name: `connected_services` → `ConnectedServicesRow`. */
export function rowName(table: string): string {
  return `${pascalCase(table)}Row`;
}

/**
 * CHECK-enum export name: table's first segment + column, e.g.
 * `audit_log`.`decision` → `AuditDecision`, `policy_entries`.`source` →
 * `PolicySource`. Matches the pinned names
 * (AuditDecision, AuditOutcome, PolicyDecision, PolicySource).
 */
export function enumName(table: string, column: string): string {
  const prefix = pascalSegment(table.split("_")[0] ?? table);
  return `${prefix}${pascalCase(column)}`;
}

function zodBase(col: ColumnMeta): string {
  if (col.enumValues) {
    return `z.enum([${col.enumValues.map((v) => JSON.stringify(v)).join(", ")}])`;
  }
  switch (col.sqlType) {
    case "TEXT":
      return "z.string()";
    case "INTEGER":
    case "REAL":
      return "z.number()";
    default: {
      const exhaustive: never = col.sqlType;
      throw new Error(`Unmapped SQL type: ${String(exhaustive)}`);
    }
  }
}

function zodField(col: ColumnMeta): string {
  return col.nullable ? `${zodBase(col)}.nullable()` : zodBase(col);
}

/**
 * Render the full generated module source for one table. Emits the row schema,
 * its inferred type (value + type share the name, a standard Zod pattern), and
 * one export per CHECK-enum column.
 */
export function renderSchema(table: string, columns: ColumnMeta[]): string {
  const RowName = rowName(table);
  const fields = columns
    .map((c) => `  ${c.name}: ${zodField(c)},`)
    .join("\n");

  const enumExports = columns
    .filter((c) => c.enumValues)
    .map((c) => {
      const Name = enumName(table, c.name);
      return (
        `export const ${Name} = ${RowName}.shape.${c.name};\n` +
        `export type ${Name} = z.infer<typeof ${Name}>;`
      );
    })
    .join("\n\n");

  return (
    // REUSE-IgnoreStart — these strings EMIT the generated files' SPDX header;
    // they are not this file's own licensing info (that is the header above).
    `// AUTO-GENERATED by src/data/codegen/generate.ts — DO NOT EDIT.\n` +
    `// Source of truth: src/data/ddl.ts (table: ${table}). Regenerate with \`just engine-codegen\`.\n` +
    `// SPDX-FileCopyrightText: 2026 Habenula, Inc.\n` +
    `// SPDX-License-Identifier: AGPL-3.0-only\n` +
    // REUSE-IgnoreEnd
    `import { z } from "zod";\n\n` +
    `export const ${RowName} = z.object({\n${fields}\n});\n` +
    `export type ${RowName} = z.infer<typeof ${RowName}>;\n` +
    (enumExports ? `\n${enumExports}\n` : "")
  );
}
